var reasons = [
    'Junnah has a kind heart; She cares about other people’s needs before hers.',
'Junnah is empathetic; She cries when you cry and feels for you, even when you’re not crying.',
'Junnah is pretty; She is easy on the eyes.',
'Junnah has nice hair; Short or long or non-existent, it looks good.',
'Junnah is cute; She pouts and snores and still looks attractive.',
'Junnah is loving; She loves me.',
'Junnah is amazing; She can stay up really late to talk to you.',
'Junnah is punctual; She always uses proper punctuation LOL she’s also never late.',
'Junnah has a heart for kids; She loves kids and willingly plays the mom role.',
'Junnah is a mom; She has hundreds of kids in Jr Kayamm and ECKCM.',
'Junnah is an ajumma; She rocks mom jeans.',
'Junnah is a halmuni; She gets tired easily and her body aches so she needs to get a foam roller and pas.',
'Junnah is a homebody; She is always down to stay home and relax and do nothing.',
'Junnah is attractive; She makes people want to be around her and her earrings are metal so she’s magnetic.',
'Junnah is strong; She sleeps under 20 lb blankets and can pick up 32 pack water bottles and can also fight through the hardest times.',
'Junnah is hot; She has a nice bod.',
'Junnah is a good driver; She can drive for hours on no sleep and also can drift.',
'Junnah has a nice smile; She makes you want to smile back because you can feel that it’s genuine.',
'Junnah is a baby; She whines and cries but is quick to hug and love.',
'Junnah is young; She can type ridiculously fast, and spends too much time typing because she always beats her friends in the typing test.',
'Junnah has model hands; She could be a hand model for Bath and Body Works and her hands are nice to hold.',
'Junnah has long nails; She has 0.5 inch nails that could be cut shorter so she won’t cut her friend’s hands.',
'Junnah is caring; She cares for her grandparents and all those around her, and will even make videos on how to use exfoliating skin care for her friends.',
'Junnah is giving; She gives to others because she wants them to be happy, like airpods.',
'Junnah is funny; She laughs with other and at others and for others.',
'Junnah is romantic; She likes little things like flowers and notes.',
'Junnah is a movie fanatic; She’s seen everything except for Star Wars and other important movies.',
'Junnah is a gamer; She’s a diehard Cookie Runner.',
'Junnah is a vlogger; She has very artistic vlogs.',
'Junnah is a journaler; She writes things down in her journals which shows her thoughtfulness.',
'Junnah is a good cook; She can cook anything from ramen to pasta aioli.',
'Junnah is friendly; She has many friends that also consider her to be their friend.',
'Junnah is popular; She has millions of followers and friends and admirers and copycats.',
'Junnah has a nice voice; She sings well and makes you want to sing along.',
'Junnah is DDG; Drop Dead Gorgeous but she doesn’t know it.',
'Junnah is a hard worker; She works so hard that her shoulder almost falls off.',
'Junnah flexes hard; She has airpods and then she got tired of them so she gave them away and bought airpod 2.0.',
'Junnah is disciplined; She can study for the GRE on a schedule.',
'Junnah is smart; She has a BS in Audiology and Speech Pathology.',
'Junnah is Korean; She has cute pictures in a hanbok on her instagram.',
'Junnah is a show-off; She covers her face with her hands because she wants everyone to see that she has pretty fingers.',
'Junnah is old; She listens to records and has her own record player.',
'Junnah is exceptional; She gets offered promotions as manager within 2 months of her working at a store.',
'Junnah is loved; Everyone around her loves her and she is always on the good side of everyone.',
'Junnah is wild; She always tells people to rock-on with a rock hand-sign.',
'Junnah is a big baller; She spends money on $100+ shoes.',
'Junnah is Seventh Day Adventist and Korean and is going to grad school; What more could you ask for?',
'Junnah is Apple; She has airpods and a mac and an iphone, so she just needs an ipad and apple watch.',
'Junnah has pretty eyes; They’re brown and black and they are comfortable to stare into.',
'Junnah has nice lips; They’re always pink so she has natural lipstick on.',
'Junnah has nice skin; She has a rigorous skin care routine, and says that skin care is the most vital because makeup can only do so much.', 
'Junnah is selfish; She doesn’t like to share secrets.',
'Junnah is righteous; She won’t share notes on the Sabbath School lesson.',
'Junnah is rude; She’ll point out things like how wrapping a box is easy when you’re clearly struggling.',
'Junnah is multilingual; She can speak dog and human.',
'Junnah is spontaneous; She will have urges to just go out and do something, she just doesn’t.',
'Junnah reads many books; She always has a book that she’s reading so she’s educated and cultured.',
'Junnah is healthy; She eats vegetables all the time;',
'Junnah is prone to sickness; She gets sick every year at ECKCM even though all she does is hold kids as they sleep.',
'Junnah is artistic; She has a scrapbook of things that she likes and cuts ribbon with a cool little arrow.',
'Junnah is weird; She likes bbq sauce more than honey mustard.',
'Junnah is a chef; She can cut and cook gogi at Iron Age really well.',
'Junnah is brave; She has no problems with calling customer service.',
'Junnah is tired; She is perpetually emotionally and physically exhausted.',
'Junnah is energetic; She has so much energy she wakes up multiple times throughout the night.',
'Junnah is a shopaholic; She goes to the grocery store at least once a week.',
'Junnah is devoted; She is a super loyal friend and thinks of all her friends dearly.',
'Junnah is a teacher; She teaches people how to drive and the kids how to dance.',
'Junnah is a dancer; She dances for hours and hours to vbs songs.',
'Junnah is a true gift giver; She thinks a lot about what kind of gifts to give each person, and also doesn’t like receiving gifts in return.',
'Junnah is a finder; She’ll tell someone she likes them first.',
'Junnah is patient; She can deal with jokes that don’t seem like jokes and also with customers who want to return clothes because they can’t get the stains out.',
'Junnah is a flexitarian; She doesn’t eat meat except for when she wants to.',
'Junnah is a Chicagoan; She thinks that 35 degrees isn’t that cold.',
'Junnah is Seventh Day Adventist; AMEN',
'Junnah loves God; She strives to get closer to Him each day.',
'Junnah prays for others; She remembers prayer requests and actually prays for them.',
'Junnah is a leader; She can organize a big group of people and make an awesome week happen.',
'Junnah is a YouTuber; She watches vlogs and other videos on YouTube so much that she has become YouTube.',
'Junnah has 눈치; She always knows when people are sad or unhappy.',
'Junnah is successful; She has many finished lego sets in her room.',
'Junnah is a weeb; She has lots of pop figurines from different genres that are still in the box.',
'Junnah is a nerd; She only studied math for her GRE.',
'Junnah is forgiving; She is still friends with people that say mean things to her.',
'Junnah is mean; She listens to other people’s advice but not yours.',
'Junnah is ambitious; She wants to have a whole ceramic cooking set.',
'Junnah is reliable; She never forgets something you’ve asked her to do.',
'Junnah is sleepy; She is always in bed laying down.',
'Junnah is natural; She wears minimal to no makeup and looks the best that way.',
'Junnah is sincere; She tells you when she doesn’t like your glasses.',
'Junnah is a boss; She was the coordinator for Jr Kayamm. ',
'Junnah is attentive; She remembers everything you said and doesn’t get distracted.',
'Junnah has a good memory; She always remembers what she said the way she wants it to be remembered.',
'Junnah is wordy; She always wins at Words with Friends.',
'Junnah is a cheater; She always wins at Words with Friends.',
'Junnah is resourceful; She has a command hook just for her laptop charger on her wall.',
'Junnah has a green thumb; She has grown many plants before.',
'Junnah eats well; She’s good company to eat with because she can enjoy food.',
'Junnah is flexible; She can lift her leg up like Victoria Beckham.',
'Junnah is dating Ahram; She makes him the happiest person in the world.' 
]

var count = 0;

function getReason(){
  var randomNumber = Math.floor(Math.random() * (reasons.length-1));
  document.getElementById('reasonDisplay').innerHTML = 'Reason #' + randomNumber + ': ' +reasons[randomNumber];  
    
    
  var days= moment("2023-02-18").diff("2019-09-12", "days");
    document.getElementById('counter').innerHTML="Happy " + days +" Days!!";
}

function secret(){
    count++;
    if(count==5){
        document.getElementById('reasonDisplay').innerHTML= 'Reason #100: ' + reasons[99];
    }
}


